name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Debian Docker image
      run: docker build . --file Dockerfile.bullseye --tag my-image-name:$(date +%s)
    - name: Build the Ubuntu Docker image
      run: docker build . --file Dockerfile.jammy --tag my-image-name:$(date +%s)
